Add support for additional market data bar types
deephaven-examples/deephaven-ib pull request #61
Opened 2022-06-21 16:19 UTC by rbasralian

2022-06-22 17:00 UTC, chipkent requested changes

2022-06-22 17:00 UTC, chipkent commented on examples/example_beta_calc.py
> +API_PORT = 7497
clean this up.  Do we need all of these commented out?

2022-06-22 17:00 UTC, chipkent commented on src/deephaven_ib/__init__.py
> +    """Last yield."""
Do any of these need to go in the exclusion list in `request_bars_realtime`?

2022-06-22 20:22 UTC, rbasralian commented on src/deephaven_ib/__init__.py
> +    """Last yield."""
Don't believe so — think that only the existing ones (TRADES/MIDPOINT/BID/ASK) are [supported](https://interactivebrokers.github.io/tws-api/classIBApi_1_1EClient.html#a644a8d918f3108a3817e8672b9782e67)

2022-06-22 20:36 UTC, rbasralian commented on examples/example_beta_calc.py
> +API_PORT = 7497
Updated the comment to clarify these — can still remove them if you'd prefer

2022-06-23 02:42 UTC, rbasralian commented
I have read the CLA Document and I hereby sign the CLA

2022-06-24 15:37 UTC, chipkent approved these changes

2022-06-24 15:37 UTC, merged